# -*- coding: utf-8 -*-
# @Author: Pandarison
# @Date:   2018-08-29 17:57:22
# @Last Modified by:   Pandarison
# @Last Modified time: 2018-08-31 11:49:43
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['LeagueFriend.py']
DATA_FILES = ['resources']
OPTIONS = {
    'iconfile':'resources/app.icns',
    'plist':{
        'LSUIElement':True,
        'CFBundleIdentifier':'org.LeagueFriend',
        'NSAppTransportSecurity':{
            'NSAllowsArbitraryLoads':True
        }
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
