"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['LeagueFriend.py']
DATA_FILES = ['resources']
OPTIONS = {
    'iconfile':'resources/app.icns',
    'plist':{
        'LSUIElement':True,
        'CFBundleIdentifier':'org.LeagueFriend',
        'NSAppTransportSecurity':{
            'NSAllowsArbitraryLoads':True
        }
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
